# Generated by Django 4.1.2 on 2023-11-06 09:11

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5, null=True, verbose_name='Name of currency')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='Currency rate to KZT')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Date of publish')),
            ],
            options={
                'verbose_name': 'Сurrency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['published_date'], name='currency_cu_publish_10b2ce_brin'),
        ),
    ]
