# Generated by Django 4.1.2 on 2023-11-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of publish'),
        ),
    ]
